name: lipoic
description: lipoic cross-platform application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
  font_awesome_flutter: ^10.1.0
  hive: ^2.2.1
  path_provider: ^2.0.10
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/oauth/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/Noto_Sans_TC/NotoSansTC-Regular.otf
        - asset: assets/fonts/Noto_Sans_TC/NotoSansTC-Bold.otf
          weight: 700

flutter_native_splash:
  color: "#a3dfda"
  image: assets/images/logo.png
  branding: assets/images/lipoic_text.png
