name: Analyze
on: [pull_request]

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.0.4
          cache: true
      - run: flutter pub get
      - name: Analyze the code
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.0.4
          cache: true
      - name: Run tests and generate coverage
        run: |
          flutter pub get
          flutter test --coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage/lcov.info
